POST http://localhost:8000/register HTTP/1.1
content-type: application/json

{
    "name": "local",
    "password": "local"
}
###
GET   http://localhost:8000/home HTTP/1.1
content-type: application/json

{
        "cookie":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibG9jYWwiLCJpZCI6ImQyNGE2YWU1LTk5ZDEtNDc4My05M2QzLWE4NzE1MTg2MjY4YSIsImlhdCI6MTY4NjM0Mzg3NSwiZXhwIjoxNjg2MzQzOTM1fQ.qQ0vmGe1GqsriyYpzARYdXVL5tth-UcXJ5eTlRFWKG8"

}

###
POST http://localhost:8000/login HTTP/1.1
content-type: application/json

{
    "name": "local",
    "password": "local"
}